#!/bin/bash

set -e

# Launches a clean, sandboxed Chrome instance in incognito mode with a throwaway profile

# Path to Chrome executable
chrome="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

if [ "-d" != "$1" ]; then
  if [ -n "$1" ]; then
    echo "Unknown argument: $1" >&2
  fi

  "$chrome" --user-data-dir="$(mktemp -d ${TMPDIR}/chrome.XXXXXX)" --no-default-browser-check --incognito --homepage=about:blank --no-first-run --window-position=0,0
else
  > /dev/null nohup -- "$chrome" --user-data-dir="$(mktemp -d ${TMPDIR}/chrome.XXXXXX)" --no-default-browser-check --incognito --homepage=about:blank --no-first-run --window-position=0,0 &
fi
