#!/usr/bin/env ruby

require "optparse"
require "shellwords"
require "fileutils"
require "rbconfig"

PROGNAME = File.basename(__FILE__)

def main
  options = parse_args
  args = ARGV

  check_prerequisites!

  files = find_files(args, options)

  raise "No matching audio files found. \`#{PROGNAME}\` accepts files of types: ogg, flac, aac, mp1, mp2, mp3, mp4, m4a, and wav" if files.empty?

  p "Processing #{files.size} files..."

  files.each do |source|
    unless system(%Q{ffmpeg -i #{Shellwords.escape(source)} -vn -c:a #{options[:aac]} -vbr 5 #{Shellwords.escape(destfile(source, options))}})
      raise "Failed to transcode #{source.inspect}!"
    end
  end

  p "Done."
end

def destfile(file, options)
  fname = File.basename(file, File.extname(file)) + ".m4a"

  dest = (options[:dest] || ".") || File.dirname(file)
  dest = dest.empty? ? "." : dest

  FileUtils.mkdir_p(dest)

  File.join(dest, fname)
end

def parse_args
  options = {aac: "libfdk_aac"}

  OptionParser.new do |opts|
    opts.banner = "Usage: #{PROGNAME} [options]"

    opts.on("-r", "--recursive", "Recursively convert files to AAC. Only applies when directory is specified.") do
      options[:recurse] = true
    end

    opts.on("-N", "--native-aac", "Use the native ffmpeg AAC lib instead of Fraunhofer AAC (e.g., \`ffmpeg\` was not compiled with fdk-aac).") do
      options[:aac] = "aac"
    end

    opts.on("-D DIR", "--dest-dir=DIR", "Dump files to specified directory; if not specified, files are created alongside the originals.") do |dir|
      options[:dest] = dir
    end
  end.parse!

  options
end

def find_files(args, options)
  args = (options[:recurse] ? Dir.glob("**/*") : Dir["*"]) if args.empty?

  glob(args, options).select { |f| File.extname(f) =~ /\.(ogg|flac|aac|mp[\d]+|m4a|wav)$/i }
end

def glob(args, options)
  return args.select { |f| !File.directory?(f) } unless options[:recurse]

  args.reduce([]) { |all, f| File.directory?(f) ? all.concat(glob(subdir_entries(f), options)) : all << f }.select { |f| !File.directory?(f) }
end

def subdir_entries(path)
  Dir.entries(path).select { |e| !%w(. ..).include?(e) }.map { |e| File.join(path, e) }
end

def check_prerequisites!
  raise "This program requires \`ffmpeg\`; please install this package and ensure it is on your PATH before running \`#{PROGNAME}\`." unless has_ffmpeg?
end

def has_ffmpeg?
  # windows test for ffmpeg has NOT been tested! Sorry, I'm too lazy.
  is_windows? ? system("where ffmpeg 1> NUL 2>&1") : system("command -v ffmpeg &> /dev/null")
end

def is_windows?
  !!(/mswin|mingw|cygwin/.match? RbConfig::CONFIG["host_os"])
rescue
  # For Ruby <= 2.4.0; has side effects :(
  !!(/mswin|mingw|cygwin/ =~ RbConfig::CONFIG["host_os"])
end

main
