#!/bin/bash

set -e

# Sometimes, you don't care about host key checking (e.g., when using -L or -R tunnels),
# so this is just a convenience wrapper over scp so I don't f*ck up (also, I'm lazy).

<&0 scp -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" $@
